### ISSUE TITLE
Tunnel Connection Fails

### ISSUE THREAD

**Issue by gouldcs** [taher07/dockerized-react-native#1]
The steps have been followed in README.md but the tunnel connection to a mobile device fails:
```
rn_1  | [01:05:44] Tunnel URL not found (it might not be ready yet), falling back to LAN URL.
```

Furthermore, "run on ___" options don't work either, I figure this is an issue with docker lacking the necessary emulators. However, even the 'run in browser' option doesn't work.

**Comment by taher07** [comment]
It takes some time to load the tunnel url but it does eventually load and the run in browser is yet to be tested

**Comment by bajahranks** [comment]
In my terminal I can get the message 
"Developer tools running on http://0.0.0.0:19002"

However when I click on the link the page does not load.  No developer tools at all

**Comment by taher07** [comment]
Try writing the URL into the browser without the protocol
